### ISSUE TITLE
Jest validation not passing / TypeError: _this._scrollView.scrollTo is not a function

### ISSUE THREAD

**Issue by sir-gon** [react-native-community/react-native-tab-view#150]
I'm implementing the basic example in a new fresh RN 0.41.2 app.
Before integration, all jest test are passing ok, but now I'm getting this error:

```
yarn test -- -u                                                                          1 < 18:34:34
yarn test v0.20.0
$ semistandard && jest -u
 FAIL  __tests__/index.android.js (12.308s)
  ● renders correctly

    TypeError: _this._scrollView.scrollTo is not a function
      
      at TabViewPagerScroll._this._scrollTo (node_modules/react-native-tab-view/src/TabViewPagerScroll.js:73:19)
      at TabViewPagerScroll.componentDidMount (node_modules/react-native-tab-view/src/TabViewPagerScroll.js:128:192)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:13
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:8)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:1
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:14)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:22)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:15)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:6)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:23)

 FAIL  __tests__/index.ios.js (12.308s)
  ● renders correctly

    TypeError: _this._scrollView.scrollTo is not a function
      
      at TabViewPagerScroll._this._scrollTo (node_modules/react-native-tab-view/src/TabViewPagerScroll.js:73:19)
      at TabViewPagerScroll.componentDidMount (node_modules/react-native-tab-view/src/TabViewPagerScroll.js:128:192)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:13
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:8)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:1
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:14)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:22)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:15)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:6)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:23)

Test Suites: 2 failed, 2 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        14.926s, estimated 60s
Ran all test suites.
error Command failed with exit code 1.
```

I have translated the example from Readme.md to NOT use arrow functions, because I want avoid to use "not default" presets of babel or react-native.

My example is HomePage.js:
```
'use strict';

import React, { Component } from 'react';
import {
  StyleSheet
} from 'react-native';
import {Container, Header, Text, View} from 'native-base';

import {Row, Grid} from 'react-native-easy-grid';
import { TabViewAnimated, TabBar } from 'react-native-tab-view';

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  page: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  }
});

export default class HomePage extends Component {

  constructor (props) {
    super(props);

    this.state = {
      index: 0,
      routes: [
        { key: '1', title: 'First', icon: 'ios-speedometer' },
        { key: '2', title: 'Second', icon: 'ios-game-controller-b' },
        { key: '3', title: 'Third', icon: 'ios-basketball' }
      ]
    };
  }

  _handleChangeTab (index) {
    this.setState({ index: index });
  }

  _renderTabs (props) {
    return <TabBar {...props} />;
  }

  _renderScene ({ route }) {
    switch (route.key) {
      case '1':
        return <View><Text>Tab content 1</Text></View>;
      case '2':
        return <View><Text>Tab content 2</Text></View>;
      case '3':
        return <View><Text>Tab content 3</Text></View>;
      default:
        return null;
    }
  }

  render () {
    return (
      <Container>
        <Header>
          <Text>
            Hello
          </Text>
        </Header>

        <Grid>
          <Row style={{ backgroundColor: '#635DB7' }}>
            <TabViewAnimated
              style={styles.container}
              navigationState={this.state}
              renderScene={this._renderScene.bind(this)}
              renderFooter={this._renderTabs.bind(this)}
              onRequestChangeTab={this._handleChangeTab.bind(this)}
            />
          </Row>
        </Grid>
      </Container>
    );
  }
}
```

I'm not sure how to fix te library, can't you help me?

**Comment by satya164** [comment]
Please file a bug with React Native. This is an issue with the react native preset that it doesn't have a `scrollTo` method.

**Comment by kaiyuanneo** [comment]
Has this been resolved? I'm running into the same issue

**Comment by Palisand** [comment]
@kaiyuanneo Doesn't look like it, at least not in RN 0.46.1. 😞

**Comment by flavio-henrique** [comment]
Are you using Jest task runner? I ran into the same issue using Jest. You can do this workaround:

``
Element.prototype.scrollTo = () => {} 
``javascript

All Elements created after you add this code will have the scrollTo method.

https://github.com/vuejs/vue-test-utils/issues/319#issuecomment-354667621
