### ISSUE TITLE
TypeError: _this._scrollView.scrollTo is not a function

### ISSUE THREAD

**Issue by mgwidmann** [react-native-community/react-native-tab-view#344]
Generated a brand app new like so `create-react-native-app mobile`. In `App.js` pasted in the code from the readme (had to change a few minor things, could use an update). Ran `yarn test`

### Expected behaviour
Test should pass

### Actual behaviour
Test crashes with the following screen
![image](https://user-images.githubusercontent.com/5035724/30465684-77d37a3e-99a6-11e7-9c42-c5dda25a2494.png)

### Code sample, screenshots
Heres the full (textual) error and stack trace
```
TypeError: _this._scrollView.scrollTo is not a function

    The error is located at:
        in TabViewPagerScroll (created by TabViewAnimated)
        in View (created by View)
        in View (created by TabViewAnimated)
        in TabViewAnimated (created by TabViewExample)
        in TabViewExample

    The error was thrown at:
        at TabViewPagerScroll._this._scrollTo (/Users/mattwidmann/code/elixir/slack_coder/mobile/node_modules/react-native-tab-view/src/TabViewPagerScroll.js:90:19),
        at TabViewPagerScroll.componentDidMount (/Users/mattwidmann/code/elixir/slack_coder/mobile/node_modules/react-native-tab-view/src/TabViewPagerScroll.js:113:259),
        at commitLifeCycles (/Users/mattwidmann/code/elixir/slack_coder/mobile/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5217:24),
        at commitAllLifeCycles (/Users/mattwidmann/code/elixir/slack_coder/mobile/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5752:9),
        at invokeGuardedCallback$1 (/Users/mattwidmann/code/elixir/slack_coder/mobile/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2003:10),
        at invokeGuardedCallback (/Users/mattwidmann/code/elixir/slack_coder/mobile/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2073:36),
        at commitAllWork (/Users/mattwidmann/code/elixir/slack_coder/mobile/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5865:19),
        at completeUnitOfWork (/Users/mattwidmann/code/elixir/slack_coder/mobile/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6005:11),
        at performUnitOfWork (/Users/mattwidmann/code/elixir/slack_coder/mobile/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6037:14),
        at workLoop (/Users/mattwidmann/code/elixir/slack_coder/mobile/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6159:26)
```

### What have you tried
Runs perfectly fine when executing the app, only an issue when testing.

Heres the full code:
```javascript
import React, { Component } from 'react';
import { Text, View } from 'react-native';
import { TabViewAnimated, TabBar } from 'react-native-tab-view';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  page: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default class TabViewExample extends Component {
  state = {
    index: 0,
    routes: [
      { key: '1', title: 'Mine' },
      { key: '2', title: 'Monitors' },
      { key: '3', title: 'Hidden' },
    ],
  };

  _handleChangeTab = (index) => {
    this.setState({ index });
  };

  _renderTab = (props) => {
    return <TabBar {...props} />;
  };

  _renderScene = ({ route }) => {
    switch (route.key) {
    case '1':
      return <View style={[ styles.page, { backgroundColor: '#F5F5F5' } ]} />;
    case '2':
      return <View style={[ styles.page, { backgroundColor: '#F5F5F5' } ]} />;
    case '3':
      return <View style={[ styles.page, { backgroundColor: '#F5F5F5' } ]} />;
    default:
      return null;
    }
  };

  render() {
    return (
      <TabViewAnimated
        style={styles.container}
        navigationState={this.state}
        renderScene={this._renderScene}
        renderFooter={this._renderTab}
        onIndexChange={this._handleChangeTab}
      />
    );
  }
}
```
And the test:
```javascript
import React from 'react';
import App from './App';

import renderer from 'react-test-renderer';

it('renders without crashing', () => {
  const rendered = renderer.create(<App />).toJSON();
  expect(rendered).toBeTruthy();
});

```

**Comment by kwes01** [comment]
how did you solved this problem?

**Comment by mgwidmann** [comment]
Never did. I did not end up using this package for this reason.

**Comment by satya164** [comment]
This is a bug with the Jest mocks in React Native and not this library.
