### ISSUE TITLE
Problem with npm package

### ISSUE THREAD

**Issue by farzadab** [react-native-community/react-native-tab-view#48]
When I try to install the package with npm, I get the error:
`npm ERR! cb() never called!`
The package `react-addons-shallow-compare` is okay, the problem is with `react-native-tab-view`

-----
my npm version: `3.10.8`
my node version: `v6.9.1`

**Comment by julienvincent** [comment]
Using yarn - I also cannot install. yarn stack:

```
error https://registry.npmjs.org/react-native-tab-view/-/react-native-tab-view-0.0.36.tgz: invalid tar file
    at Extract.Parse._startEntry (/Users/julienvincent/.nvm/versions/node/v6.7.0/lib/node_modules/yarn/node_modules/tar/lib/parse.js:149:13)
    at Extract.Parse._process (/Users/julienvincent/.nvm/versions/node/v6.7.0/lib/node_modules/yarn/node_modules/tar/lib/parse.js:131:12)
    at BlockStream.<anonymous> (/Users/julienvincent/.nvm/versions/node/v6.7.0/lib/node_modules/yarn/node_modules/tar/lib/parse.js:47:8)
    at emitOne (events.js:96:13)
    at BlockStream.emit (events.js:188:7)
    at BlockStream._emitChunk (/Users/julienvincent/.nvm/versions/node/v6.7.0/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:145:10)
    at BlockStream.resume (/Users/julienvincent/.nvm/versions/node/v6.7.0/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:58:15)
    at Extract.Reader.resume (/Users/julienvincent/.nvm/versions/node/v6.7.0/lib/node_modules/yarn/node_modules/fstream/lib/reader.js:249:34)
    at Entry.<anonymous> (/Users/julienvincent/.nvm/versions/node/v6.7.0/lib/node_modules/yarn/node_modules/tar/lib/parse.js:261:8)
    at emitNone (events.js:86:13)
```

**Comment by satya164** [comment]
I published with yarn, which was not probably a good idea. Can you try installing again? Just published 0.0.37. Can you try again?

**Comment by julienvincent** [comment]
Working 👍

**Comment by farzadab** [comment]
Thx :)
