### ISSUE TITLE
Jest/storybook/storyshots error el.getNode is not a function

### ISSUE THREAD

**Issue by andreialecu** [react-native-community/react-native-tab-view#845]
### Current behaviour

I'm trying to take snapshots of components using react native storybook [storyshots](https://storybook.js.org/docs/testing/structural-testing/)

After adding the react-native-reanimated mocks using: 

```
jest.mock('react-native-reanimated', () => require('react-native-reanimated/mock'));
```

There is one error left, getting:

```
TypeError: el.getNode is not a function

      at ref (node_modules/react-native-tab-view/lib/commonjs/TabBar.tsx:391:15)
      at commitAttachRef (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9593:7)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10834:7)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2377:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2427:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2480:31)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11041:7)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12492:5
      at Object.unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:255:12)
      at completeRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12491:13)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12420:9)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12328:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12302:3)
      at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12171:5)
      at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11986:5)
      at scheduleRootUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12585:3)
      at updateContainerAtExpirationTime (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12613:10)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12624:10)
      at create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13057:5)
      at getRenderedTree (node_modules/@storybook/addon-storyshots/dist/frameworks/react/renderTree.js:22:16)
      at node_modules/@storybook/addon-storyshots/dist/test-bodies.js:21:18
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/api/snapshotsTestsTemplate.js:35:33)
```

Also there is this from yellowbox:

```
The above error occurred in the <ScrollViewMock> component:
          in ScrollViewMock (at TabBar.tsx:364)
          in View (created by View)
          in View (at TabBar.tsx:363)
          in View (created by View)
          in View (at TabBar.tsx:330)
          in TabBar (created by Pager)
          in Pager (at TabView.tsx:126)
          in View (created by View)
          in View (at TabView.tsx:125)
          in TabView (created by FriendList)
          in View (created by View)
          in View (at View.js:9)
          in ViewNB (created by Styled(ViewNB))
          in Styled(ViewNB) (created by FriendList)
          in FriendList (created by FriendsRoute)
          in View (created by View)
          in View (at View.js:9)
          in ViewNB (created by Styled(ViewNB))
          in Styled(ViewNB) (created by FriendsRoute)
          in FriendsRoute (created by SceneComponent)
          in SceneComponent (at SceneMap.tsx:16)
          in View (created by View)
          in View (at SceneView.tsx:92)
          in SceneView (at TabView.tsx:165)
          in View (created by View)
          in View (at Pager.tsx:667)
          in PanGestureHandler (at Pager.tsx:659)
          in Pager (at TabView.tsx:126)
          in View (created by View)
          in View (at TabView.tsx:125)
          in TabView (created by MainScreen)
          in View (created by View)
          in View (at View.js:9)
          in ViewNB (created by Styled(ViewNB))
          in Styled(ViewNB) (created by MainScreen)
          in BVLinearGradient (created by _class)
          in _class (created by LinearGradient)
          in LinearGradient (created by MyMainGradient)
          in View (created by View)
          in View (created by ImageBackground)
          in ImageBackground (created by MyMainGradient)
          in View (created by View)
          in View (created by MyMainGradient)
          in MyMainGradient (created by glamorous(MyMainGradient))
          in glamorous(MyMainGradient) (created by MainScreen)
          in MainScreen
```

Looks like ScrollViewMock is correctly used, I'm not sure why the `el.getNode` function isn't there. I'm not able to find any related errors reported upstream in `react-native`, and I assume there would reports for this - it should be relatively common to work with.

### Expected behaviour

Should not error, I'm not sure whether some mock is missing that could be provided. 

### What have you tried

Added react-native-reanimated mocks, this is the only error left.

The error is here: https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBar.tsx#L391

It seems that `el.getNode` is `undefined` in the jest/mock context.

Any ideas?

### Your Environment

| software                     | version
| ---------------------------- | -------
| react-native                 | 0.59.10
| react-native-tab-view        | 2.9.0
| react-native-gesture-handler | 1.2.1
| react-native-reanimated | 1.1.0

**Comment by andreialecu** [comment]
Replacing the offending code with `this.scrollView = el && (el.getNode ? el.getNode() : el);` made it work.

I found some possibly related info about this here: https://github.com/facebook/react-native/issues/19650

I'm not familiar with `.getNode()`. I assume it's on `Animated.ScrollView`, but in the mock context a normal mocked ScrollView is used, which doesn't have that method. 

Would this be a correct fix? Should I send a PR?

**Comment by andreialecu** [comment]
Seems that the `Animated.ScrollView` is replaced with a regular `ScrollView` by the react-native-reanimated mock here: https://github.com/kmagiera/react-native-reanimated/blob/master/mock.js#L35
